name: install
description: cache npm install

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

      # Ensure uses a version compatible with NPM "Trusted Publishers"
      # https://docs.npmjs.com/trusted-publishers#supported-cicd-providers
    - name: Update npm
      shell: bash
      run: npm install -g npm@latest

    - name: Install dependencies
      shell: bash
      run: npm ci
