name: manual release
env:
  CI: true
  GIT_AUTHOR_NAME: GitHub Actions Bot
  GIT_AUTHOR_EMAIL: <>
  GIT_COMMITTER_NAME: GitHub Actions Bot
  GIT_COMMITTER_EMAIL: <>
on:
  workflow_dispatch:
    inputs:
      skip_chromatic_publish:
        description: 'Should skip publishing to Chromatic'
        required: false
        default: false
        type: boolean
      release_type:
        description: 'Type of the release'
        required: false
        default: 'prerelease'
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease
          - prepatch
          - preminor
          - premajor

jobs:
  chromatic-deployment:
    if: github.event.inputs.skip_chromatic_publish == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - name: Compile Package
        run: npm run compile
      - name: Build Storybook
        run: npm run build-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          workingDir: ./
          autoAcceptChanges: true

  publish_canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install
      - name: Compile package
        run: npm run compile
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Increment version
        run: |
          npm version --preid canary --no-commit-hooks ${{ github.event.inputs.release_type || 'prerelease' }}
          git push --no-verify
          git push --tags --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        run: npm publish
