name: check pull request
on:
  pull_request:
    branches: [master]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: npm run lint
      - run: npm run test
        env:
          NODE_OPTIONS: --max-old-space-size=8192
# loki does not work with React 19, related to https://github.com/vadimdemedes/ink/issues/688
#  test_visual:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/install
#      - run: npm run build-storybook
#      - run: export NODE_OPTIONS=--openssl-legacy-provider && npm run test:visual
#
#      - name: Archive screenshots
#        if: ${{ failure() }}
#        uses: actions/upload-artifact@v4
#        with:
#          name: loki-screenshots
#          path: .loki
