name: check pull request
on:
  pull_request:
    branches: [master]
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm run lint
      - run: pnpm run test
        env:
          NODE_OPTIONS: --max-old-space-size=8192

  test_visual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: pnpm run build-storybook
      - run: export NODE_OPTIONS=--openssl-legacy-provider && pnpm run test:visual

      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: loki-screenshots
          path: packages/ui/.loki
