name: check pull request
on: pull_request
env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - run: pnpm run lint
      - run: pnpm run test
        env:
          NODE_OPTIONS: --max-old-space-size=8192

  test_visual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - run: pnpm run build-storybook
      - run: pnpm run test:visual

      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: loki-screenshots
          path: packages/ui/.loki

  publish_next:
    runs-on: ubuntu-latest
    needs: [test, test_visual]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: create and publish versions
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
