name: publish release

# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  publish_release:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check Release Format
        id: check-release
        run: |
          if [[ ${{ github.head_ref }} =~ ^release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Create tag
        if: steps.check-release.outputs.match == 'true'
        id: create_tag
        run: |
          tag=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/release\///')
          echo ::set-output name=tag::$tag
      - uses: actions/checkout@v2
      - name: Set tag
        if: steps.check-release.outputs.match == 'true'
        run: |
          npx lerna publish from-git
          git tag --force ${{ steps.create_tag.outputs.tag }} -m "tag release ${{ steps.create_tag.outputs.tag }}"
          git push -f origin ${{ steps.create_tag.outputs.tag }}
